#!/usr/bin/env bash

url=${1}
start_time=$(date +%s)
repo=${url/github.com/github.com.cnpmjs.org}
echo "从镜像git cloe"
git clone ${repo}
end_time=$(date +%s)
cost_time=$[ $end_time-$start_time ]
echo "gitclone 执行时间 $(($cost_time/60))min $(($cost_time%60))s"
