#!/usr/bin/env php
<?php
class gitclone{

 public static function clone($a)
{


    
 $b= str_replace("https://github.com","https://github.com.cnpmjs.org",$a);
 echo "正在从代理clone文件".$b."\n";
 passthru( "git clone ".$b);
}


}

 

array_shift($argv);

    @call_user_func_array(['gitclone', 'clone'], $argv);
