#!/usr/bin/env php
<?php
class gitclone{

 public static function clone($a)
{


    
 $b= str_replace("https://github.com","https://github.com.cnpmjs.org",$a);
 echo "正在从代理clone文件".$b."\n";
 passthru( "git clone ".$b);
}


}

 

$arg=array_shift($argv);



if (!isset($argv[0])){
echo "使用方法 gitclone 地址 代替 git clone 地址\n";
    exit;
}
    @call_user_func_array(['gitclone', 'clone'], $argv);
